[package]
name = "dioxus-fullstack"
authors = ["Jonathan Kelley", "Evan Almloff"]
version = { workspace = true }
edition = "2021"
description = "Fullstack Dioxus Utilities"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["ui", "gui", "react", "server", "fullstack"]
resolver = "2"

[dependencies]
# server functions
server_fn = { version = "0.6.5", features = ["json", "url", "browser"], default-features = false }
dioxus_server_macro = { workspace = true }
once_cell = { workspace = true }

# axum
axum = { workspace = true, features = ["ws", "macros"], optional = true }
tower-http = { workspace = true, optional = true, features = ["fs"] }

dioxus-lib = { workspace = true }
generational-box = { workspace = true }
serde = "1.0.159"

# Dioxus + SSR
dioxus-core = { workspace = true, features = ["serialize"] }
dioxus-ssr = { workspace = true, optional = true }
hyper = { workspace = true, optional = true }
http = { workspace = true, optional = true }

# Web Integration
dioxus-web = { workspace = true, features = ["hydrate"], default-features = false, optional = true }
dioxus-interpreter-js = { workspace = true, optional = true }

futures-util = { workspace = true }
futures-channel = { workspace = true }
ciborium = { workspace = true }
base64 = { workspace = true }
tracing = { workspace = true }
parking_lot = { version = "0.12.1", features = ["send_guard"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true, features = ["rt", "sync"], optional = true }
web-sys = { version = "0.3.61", features = ["Window", "Document", "Element", "HtmlDocument", "Storage", "console"], optional = true}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt", "sync", "rt-multi-thread"], optional = true }

[dev-dependencies]
dioxus = { workspace = true, features = ["fullstack"] }

[features]
default = ["document"]
document = ["dioxus-web?/document"]
web = ["dep:dioxus-web", "dep:web-sys"]
server = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
features = ["web"]
