[package]
name = "dioxus-server"
edition = "2021"
version.workspace = true

[dependencies]
axum = { workspace = true, features = ["ws", "macros"], optional = true }
tower-http = { workspace = true, optional = true, features = ["fs"] }
